### ISSUE TITLE
cashes_balance_cells#show (ActionView::Template::Error) "undefined method `printed_on' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1517]
## Error

An ActionView::Template::Error occurred in cashes_balance_cells#show:
```
  undefined method `printed_on' for nil:NilClass
  app/models/cash.rb:274:in `last_entry_date'
```
---
## Environment
- **Version :** 2.27.1
- **Server :** production

**Comment by burisu** [comment]
Introduced by d0661faf0f808f8cc696df580a134c34d3665f23
